export const ADD_COMMAND = 'ADD_COMMAND';
export const REMOVE_COMMAND = 'REMOVE_COMMAND';
export const MOVE_COMMAND_UP = 'MOVE_COMMAND_UP';
export const MOVE_COMMAND_DOWN = 'MOVE_COMMAND_DOWN';
export const MOVE_POINT = 'MOVE_POINT';
export const ADD_POINT = 'ADD_POINT';

export const SET_ACTIVE_COMMAND = 'SET_ACTIVE_COMMAND';

export const SET_DRAWING_MODE = 'SET_DRAWING_MODE';